### ISSUE TITLE
 Cannot find color scheme 'aura-dark'

### ISSUE THREAD

**Issue by 912-dattm** [baliestri/aura-theme#1]
<img width="1328" alt="Screen Shot 2022-03-01 at 14 52 55" src="https://user-images.githubusercontent.com/43894751/156127635-059e9ad9-fc5d-4071-bd27-3d5751676b98.png">
i get error like this, is there any way to fix it? tks

**Comment by baliestri** [comment]
Did you reopen the editor after installation? Run `:PackerSync` or `:PlugInstall`

**Comment by 912-dattm** [comment]
> Did you reopen the editor after installation? Run `:PackerSync` or `:PlugInstall`

yes

**Comment by baliestri** [comment]
> yes

Remove colorscheme from `init.lua`, sync and add colorscheme back to `init.lua`

**Comment by 912-dattm** [comment]
> 
<img width="1128" alt="Screen Shot 2022-03-03 at 22 02 18" src="https://user-images.githubusercontent.com/43894751/156591219-571e19f8-ae57-470b-a0c1-c3e747ee7c57.png">
still not work :(

**Comment by baliestri** [comment]
> still not work :(

`aura-theme` is not a colorscheme, the available colorschemes are described here: https://github.com/baliestri/aura-theme/tree/feat/neovim-port/packages/neovim#usage

**Comment by 912-dattm** [comment]
> `aura-theme` is not a colorscheme, the available colorschemes are described here: https://github.com/baliestri/aura-theme/tree/feat/neovim-port/packages/neovim#usage

it works with the current file but when opening a new file it gives an error

https://user-images.githubusercontent.com/43894751/156621705-c0ae72f9-9ed9-4633-b211-f6bd41e28d3b.mov

**Comment by baliestri** [comment]
> it works with the current file but when opening a new file it gives an error

I believe I found the problem, I just fixed it, please update and try again

**Comment by 912-dattm** [comment]
> > it works with the current file but when opening a new file it gives an error
> 
> I believe I found the problem, I just fixed it, please update and try again

still the same bro :(

**Comment by baliestri** [comment]
> still the same bro :(

I believe it is now resolved, remove the plugin completely and follow the instructions at https://github.com/baliestri/aura-theme/tree/feat/neovim-port/packages/neovim

**Comment by 912-dattm** [comment]
> 

it works perfectly but the tab's color is hard to distinguish
<img width="882" alt="Screen Shot 2022-03-04 at 22 33 40" src="https://user-images.githubusercontent.com/43894751/156792783-e14d6687-dff0-44dd-88b2-8535c39d98e7.png">
<img width="877" alt="Screen Shot 2022-03-04 at 22 33 52" src="https://user-images.githubusercontent.com/43894751/156792805-3b4cf508-f369-4e2f-adb6-46e5d5c7863f.png">

**Comment by baliestri** [comment]
> it works perfectly but the tab's color is hard to distinguish

Okay, I'll start making adjustments soon

**Comment by 912-dattm** [comment]
> > it works perfectly but the tab's color is hard to distinguish
> 
> Okay, I'll start making adjustments soon

you should also change the CursorLine colour. so thanks 👍

**Comment by victor4pinheiro** [comment]
I'm having the same error.

I installed and got the same error from screenshotof @sieuda0kid . After this, I uninstalled the theme and reinstalled the theme and doesn't change anything.
After this I check if packer was downloading correctly the files and yes, it's doing right.

![image](https://user-images.githubusercontent.com/60495567/163582013-46d8f1ac-8a03-48a1-8aa0-883d3dc96e79.png)

**Comment by baliestri** [comment]
> I'm having the same error.
> 
> I installed and got the same error from screenshotof @sieuda0kid . After this, I uninstalled the theme and reinstalled the theme and doesn't change anything. After this I check if packer was downloading correctly the files and yes, it's doing right.

Does your configuration in packer look like this?
```lua
use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate' } -- Recommended, not required.
use {
  'baliestri/aura-theme',
  branch = 'feat/neovim-port',
  rtp = 'packages/neovim',
  config = function()
    vim.cmd("colorscheme aura-dark") -- Or any Aura theme available
  end
}
```
I also don't understand why it doesn't appear in the colorschemes command, at least in vim-plug it seems to work normally
