### ISSUE TITLE
Cannot find color scheme 'aura-dark'

### ISSUE THREAD

**Issue by baliestri** [baliestri/aura-theme#2]
I'm having the same error.

I installed and got the same error from screenshotof @sieuda0kid . After this, I uninstalled the theme and reinstalled the theme and doesn't change anything.
After this I check if packer was downloading correctly the files and yes, it's doing right.

![image](https://user-images.githubusercontent.com/60495567/163582013-46d8f1ac-8a03-48a1-8aa0-883d3dc96e79.png)

_Originally posted by @victor4pinheiro in https://github.com/baliestri/aura-theme/issues/1#issuecomment-1100139993_

**Comment by baliestri** [comment]
Does your configuration in packer look like this? @victor4pinheiro
```lua
use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate' } -- Recommended, not required.
use {
  'baliestri/aura-theme',
  branch = 'feat/neovim-port',
  rtp = 'packages/neovim',
  config = function()
    vim.cmd("colorscheme aura-dark") -- Or any Aura theme available
  end
}
```
I also don't understand why it doesn't appear in the colorschemes command, at least in vim-plug it seems to work normally

**Comment by victor4pinheiro** [comment]
Yes.
Actually I tried the two ways: set colorscheme like this and set colorscheme on init.lua and still seeing the same error.

**Comment by baliestri** [comment]
![image](https://user-images.githubusercontent.com/46748996/163586584-bd7bea87-316f-4aa0-bf5a-36f196273588.png)
It's working here, I really don't know what's happening on yours, did you sync it?

**Comment by victor4pinheiro** [comment]
Yes. I'll check if I forgot something

**Comment by baliestri** [comment]
You can call me on Discord if you want: `baliestri#0001`
